#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

python3 ./gen-readme.py
BRANCH=$(git branch --show-current)
COMMIT=$(git rev-parse --short HEAD)
echo "build: $BRANCH-$COMMIT" > ./_data/version.yml
git add ./_data/version.yml ./README.md
