# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DIY synths database
description: Curated collection of DIY-friendly hardware synthesizers and related musical equipment you can build on your own. All open source.

# Theme settings
db: db.json
pics: pics/
header_pic: pics/meta/header.jpeg
sharing_pic: pics/meta/norns-og.jpg
accent_color: ffcc5f
favicon_text: DIY

# Build settings
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
source: .
destination: ./docs
permalink: /:categories/:title
theme:
giscus: true
plugins:
  - jekyll-feed

exclude:
  - Dockerfile
  - README.md
  - dev.md
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache/
